// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _LandingPageLayout = "_LandingPageLayout";
                public readonly string _Layout = "_Layout";
                public readonly string _LoginLayout = "_LoginLayout";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _MailLayout = "_MailLayout";
                public readonly string _MenuLayout = "_MenuLayout";
                public readonly string _PublicLayout = "_PublicLayout";
                public readonly string Error = "Error";
                public readonly string Lockout = "Lockout";
                public readonly string NewLandingPage = "NewLandingPage";
                public readonly string NotFound = "NotFound";
            }
            public readonly string _LandingPageLayout = "~/Views/Shared/_LandingPageLayout.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginLayout = "~/Views/Shared/_LoginLayout.cshtml";
            public readonly string _LoginPartial = "~/Views/Shared/_LoginPartial.cshtml";
            public readonly string _MailLayout = "~/Views/Shared/_MailLayout.cshtml";
            public readonly string _MenuLayout = "~/Views/Shared/_MenuLayout.cshtml";
            public readonly string _PublicLayout = "~/Views/Shared/_PublicLayout.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Lockout = "~/Views/Shared/Lockout.cshtml";
            public readonly string NewLandingPage = "~/Views/Shared/NewLandingPage.cshtml";
            public readonly string NotFound = "~/Views/Shared/NotFound.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string Bootstrap3Pagination = "Bootstrap3Pagination";
            }
            static readonly _PartialViewsClass s_PartialViews = new _PartialViewsClass();
            public _PartialViewsClass PartialViews { get { return s_PartialViews; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialViewsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Fonts = "_Fonts";
                    public readonly string _Footer = "_Footer";
                    public readonly string _Header = "_Header";
                    public readonly string _HeaderAccount = "_HeaderAccount";
                    public readonly string _HeaderMenu = "_HeaderMenu";
                    public readonly string _HeaderNotifications = "_HeaderNotifications";
                    public readonly string _Notification = "_Notification";
                    public readonly string _Scripts = "_Scripts";
                    public readonly string _Style = "_Style";
                    public readonly string _Traffic = "_Traffic";
                }
                public readonly string _Fonts = "~/Views/Shared/PartialViews/_Fonts.cshtml";
                public readonly string _Footer = "~/Views/Shared/PartialViews/_Footer.cshtml";
                public readonly string _Header = "~/Views/Shared/PartialViews/_Header.cshtml";
                public readonly string _HeaderAccount = "~/Views/Shared/PartialViews/_HeaderAccount.cshtml";
                public readonly string _HeaderMenu = "~/Views/Shared/PartialViews/_HeaderMenu.cshtml";
                public readonly string _HeaderNotifications = "~/Views/Shared/PartialViews/_HeaderNotifications.cshtml";
                public readonly string _Notification = "~/Views/Shared/PartialViews/_Notification.cshtml";
                public readonly string _Scripts = "~/Views/Shared/PartialViews/_Scripts.cshtml";
                public readonly string _Style = "~/Views/Shared/PartialViews/_Style.cshtml";
                public readonly string _Traffic = "~/Views/Shared/PartialViews/_Traffic.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
