// <auto-generated />
namespace MaProgramez.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Cardtransactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cardtransactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201506212106247_Card transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
