// <auto-generated />
namespace MaProgramez.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DescriptionpeSlot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescriptionpeSlot));
        
        string IMigrationMetadata.Id
        {
            get { return "201506182017066_Description pe Slot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
