// <auto-generated />
namespace MaProgramez.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkingWeekStartDateonSlotTimeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkingWeekStartDateonSlotTimeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201507082044093_WorkingWeekStartDate on SlotTimeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
